Set embedded Scala compiler setting 'usejavacp' to true when building standalone JAR.
Leaving it to 'false` prevents the compiler from finding the reflection library,
and triggers the following error:

> Error: object scala in compiler mirror not found.

On the other hand, setting it to 'true' somehow breaks reflection when running tests.

We therefore use the `sbt-buildinfo` plugin to differentiate between the
standard and the standalone builds.